import os

AUTHORIZED_CHANNEL = os.getenv("AUTHORIZED_CHANNEL")
AUTHORIZED_ROLE = os.getenv("AUTHORIZED_ROLE")
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
EC2_INSTANCE_NAME = os.getenv("EC2_INSSTANCE_NAME")
REGION = os.getenv("REGION")
RCON_PASSWORD = os.getenv("RCON_PASSWORD")
MC_CHANNEL_ID = int(os.getenv("MC_CHANNEL_ID"))
SERVER_CHECK_INTERVAL = int(os.getenv("SERVER_CHECK_INTERVAL"))
